config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: [:destroy]
  resources :pets do
    resources :bookings, only: [:new, :create, :index]
  end
  resources :bookings, only: [:show, :edit, :update, :destroy]
  get '/dashboard', to: 'dashboard#dashboard', as: :dashboard
  root to: "pets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  enum status: [:pending, :approved, :denied], _default: :pending
  belongs_to :user
  belongs_to :pet
  validates :start_date, :end_date, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  PET = ["Dog", "Cat", "Bird", "Other"]
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :pet_type, inclusion: { in: PET }
  has_one_attached :photo
  enum available: [:Available, :Unavailable, :Booked]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :pets
  has_one_attached :photo
  validates :first_name, :last_name, :address, :email, :user_type, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum user_type: [:owner, :sitter, :both]
  validates :email, format: { with: /\A.*@.*\.com\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :user_type, :email, :photo])
    @skip_footer = true
    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address,:user_type, :email])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    @pet = Pet.find(params[:pet_id])
  end

  def show
    @booking = Booking.find(params[:id])
    @sitter = User.find(@booking.user_id)
    @pet = Pet.find(@booking.pet_id)
    @owner = User.find(@pet.user_id)
  end

  def new
    @booking = Booking.new
    @pet = Pet.find(params[:pet_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @pet = Pet.find(params[:pet_id])
    @booking.pet = @pet
    @user = current_user
    @booking.user_id = @user.id
    if @booking.save
      redirect_to pets_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @pet = @booking.pet
    @booking.update(booking_params)
    if @booking.status == "approved"
      @pet.available = 2
      @pet.save
    end

    if @booking.status == "pending" || @booking.status == "denied"
      @pet.available = 0
      @pet.save
    end
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to pets_path(@pet)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :price)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    @user = current_user
    @pets = current_user.pets
    # Owner
    @ownerbookings = Booking.where(pet: @pets)
    # Sitter
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_list, only: [:show, :destroy]
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
    @user = User.find(@pet.user_id)
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking = Booking.where(pet_id: @pet.id).first
    @pet.update(pet_params)
    if @pet.available == "Unavailable"
      @booking.status = 0
      @booking.save
    end
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pet_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :pet_type, :description, :photo, :user_id, :available, :available_from, :available_till, :booking_requirements)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # Alter the route once the user sign's up
  def after_sign_up_path_for(resource)
    stored_location_for(resource) || user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  # As a User, I can view my profile
  def show
    @pets = User.find(params[:id]).pets
  end

  # As a user I can edit and update my profile
  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :user_type, :photo, :profile)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Edit this Booking!</h1>

<%= simple_form_for [@pet, @booking] do |f| %>
  <%= f.input :start_date, default: @pet.available_from,  as: :date,
                              order: [:day, :month, :year] %>
  <%= f.input :end_date, default: @pet.available_till, as: :date,
                              order: [:day, :month, :year] %>
  <%= f.input :status, collection: Booking.statuses.keys %>
  <%= f.input :price %>
  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<h1 class = "">Below are the bookings for <%= Pet.find(params[:pet_id]).name %></h1>
<br>
<ul>
  <% @bookings.each do |booking| %>
    <div class="container">
      <div class="row">
          <% if (booking.pet.available == "Available" || booking.pet.available == "Booked") && booking.pet.user == current_user && booking.pet == @pet %>
              <li><%= link_to "Booking ID: #{booking.id} Date: #{booking.start_date.strftime("%d %B")} Status: #{booking.status}", booking_path(booking) %></li>
          <% end %>
      </div>
    </div>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<% if current_user.user_type != "owner" %>
  <div class="p-5">
    <h1>Apply to Be a Sitter for <%= @pet.name %>!</h1>
    <h3>Requires a Sitter for <%= @pet.available_from %> - <%= @pet.available_till %></h3>
    <br>
    <div class="p-10">
      <%= simple_form_for [@pet, @booking] do |f| %>
        <%= f.input :start_date, default: @pet.available_from,  as: :date,
                                    order: [:day, :month, :year]  %>
        <%= f.input :end_date, default: @pet.available_till, as: :date,
                                    order: [:day, :month, :year]  %>
        <%= f.input :price, hint: ("Please submit a Quote for the Owner to Review") %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/bookings/show.html.erb
<div class="p-5">
  <h1>Booking ID: <%= @booking.id %></h1>

  <ul class="list-group">
    <li class="list-group-item"><strong>Pet: </strong><%= @pet.name.capitalize %></li>
    <li class="list-group-item"><strong>Owner: </strong><%= @owner.first_name.capitalize %></li>
    <li class="list-group-item"><strong>Sitter: </strong><%= @sitter.first_name.capitalize %></li>
    <li class="list-group-item"><strong>Start Date: </strong><%= @booking.start_date %></li>
    <li class="list-group-item"><strong>End Date: </strong><%= @booking.end_date %></li>
    <li class="list-group-item"><strong>Price: </strong><%= @booking.price %></li>
    <li class="list-group-item"><strong>Current Status: </strong><%= @booking.status.capitalize %></li>
  </ul>

  <% if @pet.user == current_user %>
    <%= simple_form_for (@booking) do |f| %>
      <%= f.input :status, collection: Booking.statuses.keys %>
      <%= f.submit %>
      <%= link_to "Edit", edit_booking_path(@booking) %><br><br>
    <% end %>
  <% end %>

  <%= link_to "Back to Home", pets_path %> <br> <br>
  <%= link_to "Back to Bookings", pet_bookings_path(@booking) %> <br><br>
  <%= link_to "Delete",
              booking_path(@booking),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</div>

app/views/dashboard/dashboard.html.erb
<div class="container">
  <h2 class = "mt-5 ml-4">Dashboard</h2>
  <ul class="nav nav-pills mb-4 mt-4 ml-4" id="pills-tab" role="tablist">
    <% if current_user.user_type != "sitter" %>
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Your Pets</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Your Pets Booked</a>
    </li>
    <% end %>
    <% if current_user.user_type != "owner" %>
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Applied Bookings</a>
      </li>
    <% end %>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="container mb-5">
        <div class="container">
          <div class="row">
            <% @pets.each do |pet| %>
              <div class="col-4">
                <div class="card">
                  <%= cl_image_tag pet.photo.key, height: 300, width: 400, class: "w-100", crop: :fill %>
                  <div class="card-body p-2 ml-3 mt-3">
                    <h4 class="card-title"><%= pet.name %></h4>
                    <p class="card-text"><%= pet.description %></p>
                    <% if pet.available != "Booked" && pet.available == "Available" %>
                      <p class="card-text text-success">Requires a Sitter</p>
                    <% else %>
                      <p class="card-text text-secondary">Doesnt Require a Sitter</p>
                    <% end %>
                    <%= link_to "See Profile", pet_path(pet), class: "btn btn-outline-primary mb-4 mt-3 " %>
                    <%= link_to "Edit Profile", edit_pet_path(pet), class: "btn btn-outline-primary mb-4 ml-3 mt-3" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <div class="container mb-5">
        <div class="container">
          <div class="row">
            <% @ownerbookings.each do |booking| %>
              <div class="col-4">
                <div class="card mb-2">
                  <%= cl_image_tag booking.pet.photo.key, height: 300, width: 400, class: "w-100", crop: :fill %>
                  <div class="p-2">
                    <p class="card-title m-3"><strong>Pet's Name:</strong><%= booking.pet.name %></p>
                    <p class="card-title m-3"><strong>Sitter: </strong><%= booking.user.first_name %> <%= booking.user.last_name %></p>
                    <p class="card-text m-3"><strong>Dates: </strong><%= booking.start_date.strftime("%d %B") %> to <%= booking.end_date.strftime("%d %B") %></p>
                    <p class="card-text m-3"><strong>Booking: </strong><%= booking.status.capitalize %></p>
                    <p class="card-text m-3 "><strong>Price: $</strong><%= booking.price %></p>
                    <% if booking.status == "pending" %>
                      <div class="d-flex m-3 mb-3">
                        <%= link_to "Approve", booking_path(booking, booking: { status: "approved" }), method: :patch, class: "btn btn-outline-success custom" %>
                        <%= link_to "Deny", booking_path(booking, booking: { status: "denied" }), method: :patch, class: "btn btn-outline-danger custom" %>
                      </div>
                    <% end %>
                    <%= link_to "View Sitter", user_path(booking.user_id), class: "btn btn-outline-primary custom1 pl-3 pr-4 ml-3 mb-5" %>
                        <%= link_to "View Booking", booking_path(booking), class: "btn btn-outline-primary custom1  ml-1 mb-5" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
      <div class="container mb-5">
        <div class="container">
          <div class="row">
            <% @bookings.each do |booking| %>
              <div class="col-4">
                <div class="card mb-2">
                  <%= cl_image_tag booking.pet.photo.key, height: 300, width: 400, class: "w-100", crop: :fill %>
                  <div class= "p-2">
                    <p class="card-title"><strong>Pet's Name: </strong><%= booking.pet.name %></p>
                    <p class="card-title"><strong>Owner: </strong><%= booking.pet.user.first_name %> <%= booking.pet.user.last_name %></p>
                    <p class="card-text"><strong>Dates: </strong><%= booking.start_date %> to <%= booking.end_date %></p>
                    <p class="card-text"><strong>Booking: </strong><%= booking.status.capitalize %></p>
                    <p class="card-text"><strong>Price: $</strong><%= booking.price %></p>
                  </div>
                  <%= link_to "View Booking", booking_path(booking), class: "btn btn-primary" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paws</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>

    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "/devise/shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" unless @skip_footer %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container m-10">
  <%= simple_form_for(pet) do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :pet_type, :collection => %w[Dog Cat Bird Other] %>
    <%= f.input :available, :collection => %w[Available Unavailable Booked], input_html: {id: "availability-dropdown"} %>
    <div class = "availability-fields">
      <%= f.input :available_from,
                  as: :date,
                  order: [:day, :month, :year],
                  hint: ("Please specify the days you require a sitter") %>
      <%= f.input :available_till,
                  as: :date,
                  order: [:day, :month, :year] %>
      <%= f.input :booking_requirements, hint: ("Please specify any booking requirements")  %>
    </div>
    <%= f.submit  %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<div class="p-5">
  <%= render "form", pet: @pet %>
</div>

app/views/pets/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide mb-5" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" id = "cover">
    <div class="carousel-item active">
      <img class="d-block w-100" style = "height: 500px" src= "<%= image_path "1.png" %>" alt="First slide">
      <div class="cover mb-4 d-flex align-items-center justify-content-center">
        <div class="text-center text-white">
          <h1>Save any kind of movies</h1>
          <h3 class="typed-js"></h3>
        </div>
      </div>
    </div>
    <div class="carousel-item" id = "cover">
      <img class="d-block w-100" style = "height: 500px" src= "<%= image_path "2.png" %>" alt="Second slide">
    </div>
    <div class="carousel-item" id = "cover">
      <img class="d-block w-100" style = "height: 500px" src="<%= image_path "3.png" %>" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container mt-3">
  <h3 class = "text-center mb-5">Pets that need a Sitter!</h3>
  <div class="row">
    <% @pets.each do |pet| %>
      <%# Show all the pets that require a sitter, hide booked pets %>
      <% if pet.available == "Available" %>
        <div class="col-4">
          <div class="card">
            <%= cl_image_tag pet.photo.key, height: 300, width: 400, class: "w-100", id: "w-100", crop: :fill %>
            <div class="card-body">
              <h4 class="card-title"><%= "#{pet.name} (#{pet.pet_type})" %></h4>
              <p class="card-text"><%= pet.description %></p>
              <p class="card-text"><%= "Dates: #{pet.available_from} - #{pet.available_till}" %></p>
              <%= link_to "See Profile", pet_path(pet), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="p-5">
  <%= render "form", pet: @pet %>
</div>

app/views/pets/show.html.erb
<div class="container p-5 " >
  <div class="row g-5">
    <div class="col-7">
      <div class="card shadow-sm" >
        <%= cl_image_tag @pet.photo.key, height: 300, width: 400, class: "w-100", id: "w-100", crop: :fill %>
        <div class="card-body">
          <h4 class="card-title"><%= @pet.name %></h4>
          <p class="card-text"><%= @pet.description %></p>
          <% if @pet.available == "Available" %>
            <p class="text-success">Requires a Sitter </p>
            <p class="card-text"><strong>Dates: </strong><%= "#{@pet.available_from} - #{@pet.available_till}" %></p>
            <p class="card-text"><strong>Requirements: </strong><%= @pet.booking_requirements %></p>
          <% elsif @pet.available == "Booked" %>
            <p class="text-success">This Pet is Booked</p>
          <% elsif @pet.available == "Unavailable" %>
            <p class="text-warning">Doesnt Require a Sitter</p>
          <% end %>
          <% if current_user == @user %>
            <%= link_to "Edit", edit_pet_path(@pet) %> |
            <%= link_to "Delete",
                        pet_path(@pet),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %>
            <br>
          <% end %>
          <% # Cant view the bookings if its not your pet i.e. Only pet owners can view the bookings from this page %>
          <% if @pet.user == current_user %>
            <%= link_to "View Bookings", pet_bookings_path(@pet) %>
          <% elsif current_user.user_type != "owner" && @pet.available == "Available" %>
            <%= link_to "Apply to be the Sitter", new_pet_booking_path(@pet), class: "btn btn-primary btn-block mb-2" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <%= cl_image_tag @user.photo.key, height: 300, width: 400, class: "w-100", crop: :fill %>
        <div class="d-flex p-1 mt-2">
          <div class="profile container">
            <div class="card-body">
              <h6 class="text-center"><strong>Contact this Pet's Owner</strong></h6>
              <p class="card-text text-center"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></p>
              <%= mail_to "#{@user.email}", "Contact #{@user.first_name.capitalize}", class: "btn btn-primary btn-block mb-2 " %>
              <hr>
              <p style="text-align:center;">Cancellation policy: Flexible</p>
              <div class="credit-cards" style="text-align:center; width: 100%">
                <img height="40" src="https://shoplineimg.com/assets/footer/card_visa.png"/>
                <img height="40" class = "ml-3" src="https://shoplineimg.com/assets/footer/card_master.png"/>
                <img height="40" class = "ml-3" src="https://shoplineimg.com/assets/footer/card_paypal.png"/>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <h2>Contact Us:</h2>
  <br>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright © 2021 Paws. All Rights Reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <a id="logo" href="<%= root_path %>"><%= image_tag "logo.jpg", width: "50" %></a>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <p id="screen-name">Hi, <%= current_user.first_name.capitalize %> |
        <% if current_user.user_type == "both" %>
          Both Owner & Sitter</p>
        <% else %>
          <%= current_user.user_type.capitalize %> Profile</p>
        <% end %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
             <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://miro.medium.com/max/720/1*W35QUSvGpcLuxPo3SRTH4w.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.user_type == "owner" || current_user.user_type == "both" %>
              <%= link_to "Add Pet", new_pet_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<div class="p-5">
  <h2>Edit</h2>
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "first-name" } %>

      <%= f.input :last_name,
                  required: true,
                  input_html: { autocomplete: "last-name" } %>
      <%= f.input :address,
                  required: true,
                  input_html: { autocomplete: "address" } %>
      <%= f.input :profile, hint: ("Your personal Bio") %>
      <%= f.input :photo, as: :file %>
      <%= f.input :user_type, hint: ("If you select an owner profile you will not be able to sit pets"), :collection => %w[owner sitter both] %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Update" %>
    </div>
  <% end %>
  <%= link_to "Back", :back %>
</div>

app/views/users/show.html.erb
<div id="profile">
  <div class="d-flex">
    <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill, class: "rounded" %>
    <div class="info pl-5">
      <h4><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h4>
      <p><%= @user.email %></p>
      <p><%= @user.address.capitalize %></p>
      <p><strong>User Type: </strong><%= @user.user_type.capitalize %></p>
      <%# If the user viewing this page is not viewing his/her own profile hide these actions %>
      <% if current_user == @user %>
        <div class="action-routes">
          <td><%= link_to "Edit Profile", edit_user_path(@user), class: "text-warning text-decoration-none mr-3" %></td>
          <td><%= link_to "Change Password", edit_user_registration_path(@user), class: "text-warning text-decoration-none" %></td>        </div>
      <% end %>
    </div>
  </div>
  <br>
  <% if @user.profile %>
    <h6><strong>Profile</strong></h6>
    <p><%= @user.profile %></p>
  <% end %>
</div>
<% if @user.user_type != "sitter" %>
  <br><hr>
  <h3 class='text-center mb-5'>Your Pets</h3>
<% end %>
<div class="pets container mb-5">
  <div class="cards d-flex">
    <% @pets.each do |pet| %>
      <div class="card-user">
        <%= cl_image_tag pet.photo.key, height: 300, width: 400, class: "w-100", crop: :fill %>
        <div class="card-body">
          <h4 class="card-title"><%= pet.name %></h4>
          <p class="card-text"><%= pet.description %></p>
          <% if pet.available == "Available" || pet.available == 0%>
            <p class="text-success">Requires a Sitter</p>
          <% elsif pet.available == "Booked" || pet.available == 2 %>
            <p class="text-success">This Pet is Booked</p>
          <% else %>
            <p class="text-warning">Doesnt Require a Sitter</p>
          <% end %>
          <%= link_to "See Profile", pet_path(pet), class: "btn btn-primary" %>
          <%= link_to "Edit Profile", edit_pet_path(pet), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>